#########################################################################
# Title:         Cloudbox: Nginx Role                                   #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/Cloudbox/Cloudbox                   #
# Docker Image:  lscr.io/linuxserver/nginx                                      #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Nginx Tasks
# This is the main task file for the Nginx role. It installs and configures
# Nginx, a web server.

# Include the cloudflare-dns role to set the DNS record for the nginx
# subdomain.
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare-dns
  vars:
    subdomain: "{{ nginx.subdomain|default('web',true) }}"
  when: (cloudflare_enabled) and not (nginx.direct_domain|default(false,true))

# Include the cloudflare-dns role to set the DNS record for the root domain
# and www subdomain if direct_domain is enabled.
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare-dns
  vars:
    subdomain: "{{ item }}"
  with_items:
    - "{{ user.domain }}"
    - "www"
  when: (cloudflare_enabled) and (nginx.direct_domain|default(false,true))

# Create the necessary directories for Nginx configuration.
- name: Create nginx directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/nginx

# Ensure that any previous Nginx container is removed.
- name: Stop and remove any existing container
  docker_container:
    name: nginx
    state: absent

# Create and start the Nginx Docker container.
- name: Create and start container
  docker_container:
    name: nginx
    image: lscr.io/linuxserver/nginx
    pull: yes
    env:
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      VIRTUAL_HOST: "{{ (nginx.direct_domain|default(false,true)) | ternary(user.domain + ',' + 'www.' + user.domain, nginx.subdomain|default('web',true) + '.' + user.domain) }}"
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: "{{ (nginx.direct_domain|default(false,true)) | ternary(user.domain + ',' + 'www.' + user.domain, nginx.subdomain|default('web',true) + '.' + user.domain) }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/nginx:/config"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - nginx
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
