#########################################################################
# Title:         Bazarr: Suitarr Migration Tasks                        #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Suitarr Migration Tasks
# This file contains tasks for migrating from Suitarr to Bazarr.

# Check if the /opt/bazarr directory exists.
- name: Suitarr Migration | Check folder exists
  stat:
    path: /opt/bazarr
  register: folder

# Check if the /opt/bazarr/Bazarr subdirectory exists.
- name: Suitarr Migration | Check subfolder1 exists
  stat:
    path: /opt/bazarr/Bazarr
  register: subfolder1

# If both directories exist, move the contents of the subdirectory to the parent
# directory and set the correct ownership. This is to handle a change in the
# directory structure from a previous version.
- name: Suitarr Migration | Move 'Bazarr' subfolder to 'bazarr' folder
  shell: |
    mv /opt/bazarr/Bazarr/* /opt/bazarr
    chown -R {{ user.name }}:{{ user.name }} /opt/bazarr
  when: (folder.stat.exists) and (subfolder1.stat.exists)
