#########################################################################
# Title:         Cloudbox: NowShowing Role                              #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  ninthwalker/nowshowing:v2                              #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# NowShowing Tasks
# This is the main task file for the NowShowing role. It installs and
# configures NowShowing, a tool for displaying what is currently playing on
# Plex.

# Include the cloudflare-dns role to set the DNS record for the nowshowing
# subdomain.
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare-dns
  vars:
    subdomain: nowshowing
  when: cloudflare_enabled

# Ensure that any previous NowShowing container is removed.
- name: Stop and remove any existing container
  docker_container:
    name: nowshowing
    state: absent

# Create the necessary directories for NowShowing configuration.
- name: Create NowShowing directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/nowshowing

# Create and start the NowShowing Docker container.
- name: Create and start container
  docker_container:
    name: nowshowing
    image: ninthwalker/nowshowing:v2
    pull: yes
    published_ports:
      - "127.0.0.1:6878:6878"
    env:
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      VIRTUAL_HOST: "nowshowing.{{ user.domain }}"
      VIRTUAL_PORT: 6878
      LETSENCRYPT_HOST: "nowshowing.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/nowshowing:/config"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - nowshowing
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
