#########################################################################
# Title:         Cloudbox: DDClient Role                                #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  lscr.io/linuxserver/ddclient                                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# ddclient Tasks
# This is the main task file for the ddclient role. It installs and configures
# ddclient, a tool for updating dynamic DNS records.

# Ensure that any previous ddclient container is removed before creating a new one.
- name: Stop and remove any existing container
  docker_container:
    name: ddclient
    state: absent

# Create the necessary directories for ddclient configuration.
- name: Create ddclient directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/ddclient

# Create a list of subdomains to be managed by ddclient.
- name:
  set_fact:
    subdomains:
      - plex
      - plexpy
      - "{{ ombi.subdomain|default('ombi',true) }}"
      - portainer
      - organizr
      - nzbget
      - rutorrent
      - jackett
      - nzbhydra2
      - sonarr
      - radarr
      - lidarr

# Create the ddclient.conf file from the template.
- name: Import 'ddclient.conf'
  template:
    src: "ddclient.conf.j2"
    dest: "/opt/ddclient/ddclient.conf"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    force: no
  when: cloudflare_enabled

# Create and start the ddclient Docker container with the specified configuration.
- name: Create and start container
  docker_container:
    name: ddclient
    image: "lscr.io/linuxserver/ddclient:latest"
    pull: yes
    env:
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
    volumes:
      - "/opt/ddclient:/config"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - ddclient
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
