#########################################################################
# Title:         Cloudbox: Lidarr Role                                  #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  cr.hotio.dev/hotio/lidarr                                           #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Lidarr Tasks
# This is the main task file for the Lidarr role. It installs and configures
# Lidarr, a music manager for Usenet and BitTorrent users.

# Include the cloudflare-dns role to set the DNS record for the lidarr
# subdomain.
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare-dns
  vars:
    subdomain: lidarr
  when: cloudflare_enabled

# Ensure that any previous Lidarr container is removed.
- name: Stop and remove any existing container
  docker_container:
    name: lidarr
    state: absent

# Import tasks for migrating from Suitarr.
- name: Suitarr Migration Tasks
  import_tasks: "subtasks/suitarr_migration.yml"

# Create the necessary directories for Lidarr configuration.
- name: Create lidarr directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/lidarr

# Set the default volumes for the Lidarr container.
- name: Set default_volumes variable
  set_fact:
    default_volumes:
      - "/opt/lidarr:/config"
      - "/opt/scripts:/scripts"
      - "/mnt:/mnt"
      - "/mnt/unionfs/Media/Music:/music"

# Create and start the Lidarr Docker container.
- name: Create and start container
  docker_container:
    name: lidarr
    image: cr.hotio.dev/hotio/lidarr
    pull: yes
    published_ports:
      - "127.0.0.1:8686:8686"
    exposed_ports:
      - "8686"
    env:
      BACKUP: "no"
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      UMASK: 002
      VIRTUAL_HOST: "lidarr.{{ user.domain }}"
      VIRTUAL_PORT: 8686
      LETSENCRYPT_HOST: "lidarr.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
      TZ: "{{ tz }}"
    volumes: "{{ default_volumes + nzbs_downloads_path|default([]) + torrents_downloads_path|default([]) }}"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - lidarr
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
