#########################################################################
# Title:         Cloudbox: NodeJS Role                                  #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# NodeJS Tasks
# This is the main task file for the NodeJS role. It installs NodeJS and some
# global npm packages.

# Install NodeJS.
- name: Install nodejs
  shell: "curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash - && sudo apt-get install -y nodejs"
  args:
    executable: /bin/bash
  tags: nodejs

# Get the path to the nodejs binary.
- name: "Get nodejs binary path"
  shell: "command -v nodejs || true"
  register: nodejs_binary

# Get the installed version of NodeJS.
- name: "Get nodejs version"
  shell: "{{ nodejs_binary.stdout }} --version | head -n 1 | awk '{ print substr($1, 2) }'"
  register: nodejs_version
  when: nodejs_binary.stdout | trim | length > 0

# Display the installed version of NodeJS.
- name: "Display nodejs version"
  debug:
    msg: "NodeJS {{ nodejs_version.stdout }} installed."
  when: nodejs_binary.stdout | trim | length > 0

# Update npm to the latest version.
- name: Update npm
  shell: "npm install -g npm"

# Update all global npm packages.
- name: Update packages
  shell: "npm update -g"

# Get the path to the npm binary.
- name: "Get npm binary path"
  shell: "command -v npm || true"
  register: npm_binary

# Get the installed version of npm.
- name: "Get npm version"
  shell: "{{ npm_binary.stdout }} --version | head -n 1 | awk '{ print $1 }'"
  register: npm_version
  when: npm_binary.stdout | trim | length > 0

# Display the installed version of npm.
- name: "Display npm version"
  debug:
    msg: "npm {{ npm_version.stdout }} installed."
  when: npm_binary.stdout | trim | length > 0

# Install the frontail npm module.
- name: Install frontail npm module
  npm: "name={{ item }} global=yes state=present"
  with_items:
    - frontail

# Get the path to the frontail binary.
- name: "Get frontail binary path"
  shell: "command -v frontail || true"
  register: frontail_binary

# Get the installed version of frontail.
- name: "Get frontail version"
  shell: "{{ frontail_binary.stdout }} --version | head -n 1 | awk '{ print $1 }'"
  register: frontail_version
  when: frontail_binary.stdout | trim | length > 0

# Display the installed version of frontail.
- name: "Display frontail version"
  debug:
    msg: "frontail {{ frontail_version.stdout }} installed."
  when: frontail_binary.stdout | trim | length > 0

# Install the hastebin npm module.
- name: Install hastebin npm module
  npm: "name={{ item }} global=yes state=present"
  with_items:
    - hastebin

# Get the path to the hastebin binary.
- name: "Get hastebin binary path"
  shell: "command -v hastebin || true"
  register: hastebin_binary

# Display a message indicating that hastebin is installed.
- name: "Display hastebin install info"
  debug:
    msg: "hastebin installed."
  when: hastebin_binary.stdout | trim | length > 0
