#########################################################################
# Title:         Cloudbox: Heimdall Role                                #
# Author(s):     TheBradz, desimaniac                                   #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  lscr.io/linuxserver/heimdall                                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Heimdall Tasks
# This is the main task file for the Heimdall role. It installs and configures
# Heimdall, a dashboard for all your web applications.

# Include the cloudflare-dns role to set the DNS record for the heimdall
# subdomain.
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare-dns
  vars:
    subdomain: heimdall
  when: cloudflare_enabled

# Create an htpasswd file for protecting Heimdall with a password.
- name: Create htpasswd
  htpasswd:
    path: "/opt/nginx-proxy/htpasswd/{{ item }}.{{ user.domain }}"
    name: "{{ user.name }}"
    password: "{{ user.pass }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0664
  with_items:
    - heimdall

# Ensure that any previous Heimdall container is removed.
- name: Stop and remove any existing container
  docker_container:
    name: heimdall
    state: absent

# Create the necessary directories for Heimdall configuration.
- name: Create heimdall directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/heimdall

# Create and start the Heimdall Docker container.
- name: Create and start container
  docker_container:
    name: heimdall
    image: lscr.io/linuxserver/heimdall
    pull: yes
    published_ports:
      - "127.0.0.1:8078:443"
    env:
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      VIRTUAL_HOST: "heimdall.{{ user.domain }}"
      VIRTUAL_PORT: 443
      VIRTUAL_PROTO: https
      LETSENCRYPT_HOST: "heimdall.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/heimdall:/config"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - heimdall
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
