#########################################################################
# Title:         Cloudbox: Emby | Settings Task                         #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Emby Settings Tasks
# This file contains tasks for configuring Emby after it has been installed.

# Wait for the system.xml file to be created by Emby.
- name: "Settings | Wait for 'system.xml' to be created"
  wait_for:
    path: "/opt/emby/config/system.xml"
    state: present

# Wait for 10 seconds before stopping the container.
- name: "Settings | Wait 10 seconds before stopping container"
  wait_for:
    timeout: 10

# Stop the Emby container so that the configuration files can be modified.
- name: "Settings | Stop emby container"
  docker_container:
    name: emby
    state: stopped

# Copy the dlna.xml file to the Emby config directory.
- name: "Settings | Import 'dlna.xml'"
  copy:
    src: "dlna.xml"
    dest: "/opt/emby/config/dlna.xml"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    force: no

# Disable UPnP.
- name: "Settings | Set 'EnableUPnP' to 'false'"
  xml:
    path: "/opt/emby/config/system.xml"
    xpath: /ServerConfiguration/EnableUPnP
    value: "false"

# Set the public port to 80.
- name: "Settings | Set 'PublicPort' to '80'"
  xml:
    path: "/opt/emby/config/system.xml"
    xpath: /ServerConfiguration/PublicPort
    value: "80"

# Set the public HTTPS port to 443.
- name: "Settings | Set 'PublicHttpsPort' to '443'"
  xml:
    path: "/opt/emby/config/system.xml"
    xpath: /ServerConfiguration/PublicHttpsPort
    value: "443"

# Enable HTTPS.
- name: "Settings | Set 'EnableHttps' to 'true'"
  xml:
    path: "/opt/emby/config/system.xml"
    xpath: /ServerConfiguration/EnableHttps
    value: "true"

# Set the WAN DNS to the Emby subdomain.
- name: "Settings | Set 'WanDdns' to 'emby.{{ user.domain }}'"
  xml:
    path: "/opt/emby/config/system.xml"
    xpath: /ServerConfiguration/WanDdns
    value: "emby.{{ user.domain }}"

# Disable anonymous usage reporting.
- name: "Settings | Set 'EnableAnonymousUsageReporting' to 'false'"
  xml:
    path: "/opt/emby/config/system.xml"
    xpath: /ServerConfiguration/EnableAnonymousUsageReporting
    value: "false"

# Do not require HTTPS. This is handled by the reverse proxy.
- name: "Settings | Set 'RequireHttps' to 'false'"
  xml:
    path: "/opt/emby/config/system.xml"
    xpath: /ServerConfiguration/RequireHttps
    value: "false"

# Set IsBehindProxy to true.
- name: "Settings | Set 'IsBehindProxy' to 'true'"
  xml:
    path: "/opt/emby/config/system.xml"
    xpath: /ServerConfiguration/IsBehindProxy
    value: "true"

# Start the Emby container again.
- name: "Settings | Start emby container"
  docker_container:
    name: emby
    state: started
