#########################################################################
# Title:         Cloudbox: Backup | Sanity Check                        #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Sanity Check Tasks
# This file contains tasks to ensure that a backup is not already in progress.

# Check if the backup.lock file exists.
- name: "Check if 'backup.lock' is present"
  stat:
    path: "{{ playbook_dir }}/backup.lock"
  register: backup_lock

# Get the age of the backup.lock file in hours.
- name: "Get age of 'backup.lock' file"
  set_fact:
    backup_lock_age: "{{ ( (((ansible_date_time.epoch|int) - (backup_lock.stat.ctime|int)) / (60*60) ) | int )  }}"
  when: (backup_lock.stat.exists)

# Delete the backup.lock file if it is older than 2 hours.
- name: "Delete stale 'backup.lock'"
  file:
    path: "{{ playbook_dir }}/backup.lock"
    state: absent
  when: (backup_lock.stat.exists) and (backup_lock_age|int >= 2)

# If the backup.lock file exists and is less than 2 hours old, fail the playbook.
- name: "Fail when 'backup.lock' exists"
  fail:
    msg: "A Backup task is currently in progress. Please wait for it to complete."
  when: (backup_lock.stat.exists) and (backup_lock_age|int < 2)
