#########################################################################
# Title:         Cloudbox: Backup | Variables                           #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Variables Tasks
# This file contains tasks for setting and modifying variables used in the backup role.

# Remove any trailing slashes from the backup destination paths.
- name: Remove trailing forward slashes from backup paths
  set_fact:
    local_tmp: { destination: "{{ (local.destination | default('',true)) | regex_replace('\\/$', '') }}" }
    rclone_tmp: { destination: "{{ (rclone.destination | default('',true)) | regex_replace('\\/$', '') }}" }
    rsync_tmp: { destination: "{{ (rsync.destination | default('',true)) | regex_replace('\\/$', '') }}" }

# Merge the cleaned paths back into the original variables.
- name: Merge changes back
  set_fact:
    local: "{{ local | combine(local_tmp) }}"
    rclone: "{{ rclone | combine(rclone_tmp) }}"
    rsync: "{{ rsync | combine(rsync_tmp) }}"

# Restore service
# Check if the restore service is enabled and all required variables are defined.
- name: "Set 'restore_service_enabled' variable"
  set_fact:
    restore_service_enabled: "{{ true if not(
        (restore_service is undefined)
        or
        (restore_service is none)
        or
        (restore_service | trim | length == 0)
        or
        (restore_service.user is undefined)
        or
        (restore_service.user is none)
        or
        (restore_service.user | trim | length == 0)
        or
        (restore_service.pass is undefined)
        or
        (restore_service.pass is none)
        or
        (restore_service.pass | trim | length == 0)
      )
      else false }}"
