#########################################################################
# Title:            Cloudbox: Nextcloud Role                            #
# Author(s):        l3uddz, desimaniac                                  #
# URL:              https://github.com/cloudbox/cloudbox                #
# Docker Image(s):  lscr.io/linuxserver/nextcloud                               #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Nextcloud Tasks
# This is the main task file for the Nextcloud role. It installs and configures
# Nextcloud, a suite of client-server software for creating and using file
# hosting services.

# Include the MariaDB role, as Nextcloud requires a database.
- name: MariaDB Role
  include_role:
    name: mariadb

# Include the cloudflare-dns role to set the DNS record for the nextcloud
# subdomain.
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare-dns
  vars:
    subdomain: nextcloud
  when: cloudflare_enabled

# Ensure that any previous Nextcloud container is removed.
- name: Stop and remove any existing containers
  docker_container: "name={{ item }} state=absent"
  with_items:
    - nextcloud

# Create the necessary directories for Nextcloud configuration and data.
- name: Create required directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/nextcloud
    - /opt/nextcloud/conf
    - /opt/nextcloud/data

# Create and start the Nextcloud Docker container.
- name: Create and start nextcloud container
  docker_container:
    name: nextcloud
    image: "lscr.io/linuxserver/nextcloud"
    pull: yes
    published_ports:
      - "127.0.0.1:4645:443"
    env:
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      VIRTUAL_HOST: "nextcloud.{{ user.domain }}"
      VIRTUAL_PORT: 443
      VIRTUAL_PROTO: https
      LETSENCRYPT_HOST: "nextcloud.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/nextcloud/conf:/config"
      - "/opt/nextcloud/data:/data"
      - "/mnt:/mnt"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - nextcloud
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
