#########################################################################
# Title:         Cloudbox: Nethogs Role                                 #
# Author(s):     EnorMOZ                                                #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Nethogs Tasks
# This is the main task file for the nethogs role. It installs nethogs, a
# network traffic monitoring tool.

# Ensure that the nethogs package from the system's package manager is not
# installed, as we will be building from source.
- name: Make sure nethogs package is not installed
  apt: "name=nethogs state=absent"

# Install the dependencies required to build nethogs.
- name: Install nethog dependencies
  apt: name="{{ item }}" state=present update_cache=yes
  with_items:
      - build-essential
      - libncurses5-dev
      - libpcap-dev

# Clone the nethogs repository from GitHub.
- name: Pull nethogs repo from github
  git:
    repo: "https://github.com/raboof/nethogs.git"
    dest: "/var/tmp/nethogs"
    clone: yes
    version: HEAD
    force: yes
  register: diff

# Build and install nethogs from source.
- name: Build and install nethogs
  shell: |
    cd /var/tmp/nethogs
    make
    make install
    hash -r
    setcap 'cap_net_admin,cap_net_raw+pe' /usr/local/sbin/nethogs
    rm -rf /var/tmp/nethogs
  when: diff is success

# Create a symlink to the nethogs binary in /usr/local/bin.
- name: Symlink binary to /usr/local/bin
  file:
    src: "/usr/local/sbin/nethogs"
    dest: "/usr/local/bin/nethogs"
    state: link
    force: yes
  when: diff is success

# Get the installed version of nethogs.
- name: "Get nethogs version"
  shell: "/usr/local/sbin/nethogs -V | head -n 1 | awk '{print $2}' | cut -f1,2 -d'-'"
  register: nethogs_version
  when: diff is success

# Display the installed version of nethogs.
- name: "Display nethogs version"
  debug:
    msg: "nethogs {{ nethogs_version.stdout }} installed."
  when: diff is success
