#########################################################################
# Title:         Cloudbox: Kernel - Hetzner Tasks                       #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Hetzner Tasks
# This file contains tasks that are specific to Hetzner servers.

# Install pciutils, which is required for lspci.
- name: Hetzner | Install 'pciutils'
  apt: "name=pciutils state=present"

# Get information about the PCI devices, specifically the VGA controller.
- name: Hetzner | Fetch PCI info
  shell: "lspci -v -s $(lspci | grep -E '.*VGA.*Intel.*' | cut -d' ' -f 1) 2>/dev/null || :"
  register: lscpi_resp

# Check if the Hetzner blacklist file exists.
- name: Hetzner | Check if 'blacklist-hetzner.conf' exists
  stat:
    path: "/etc/modprobe.d/blacklist-hetzner.conf"
  register: blacklist_hetzner_conf

# This block is executed if an Intel i915 GPU is detected and the Hetzner
# blacklist file exists.
- name: Hetzner | Hetzner GRUB Edits Block
  block:

  # Comment out the i915 blacklist in the Hetzner blacklist file to enable the
  # Intel GPU.
  - name: Hetzner | Comment out 'i915' blacklists in 'blacklist-hetzner.conf'
    replace:
      path: "/etc/modprobe.d/blacklist-hetzner.conf"
      regexp: '(^blacklist\si915.*)'
      replace: '#\1'

  # Set a list of GRUB configuration files to check.
  - name: Hetzner | Hetzner GRUB files
    set_fact:
      hetzner_grub_files:
        - "/etc/default/grub.d/hetzner.cfg"
        - "/etc/default/grub"

  # Check if the GRUB configuration files exist.
  - name: Hetzner | Check status of GRUB files
    stat:
      path: "{{ item }}"
    loop: "{{ hetzner_grub_files }}"
    register: hetzner_grub_files_status

  # Include the tasks for editing the GRUB configuration files.
  - name: Hetzner | Hetzner GRUB edits
    include_tasks: "hetzner_grub_edits.yml"
    when: outer_item.stat.exists
    loop: "{{ hetzner_grub_files_status.results }}"
    loop_control:
      loop_var: outer_item

  when: ('i915' in lscpi_resp.stdout) and (blacklist_hetzner_conf.stat.exists)
