#########################################################################
# Title:         Cloudbox: Kernel - Restart Tasks                       #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Restart Tasks
# This file contains tasks for restarting the server after a kernel update.

# If this is a pre-install, set a fact to indicate that a reboot is required.
- name: "Restart | Set preinstall variables"
  set_fact:
    preinstall_kernel_restart: true
  when: ('preinstall' in ansible_run_tags)

# This block is executed if this is not a pre-install.
- name: Restart | Tasks for non-preinstall
  block:

  # Display a message indicating that the server will be rebooted.
  - name: Restart | Success message
    debug:
      msg:
        - "Kernel was updated."
        - "Restarting the server to apply changes..."

  # Reboot the server.
  - name: Restart | Reboot
    shell: reboot

  # This message is displayed if the reboot fails.
  - name: Restart | Reboot message
    debug:
      msg:
        - "Failed to reboot automatically."
        - "You will need to restart the server yourself for changes to take effect."

  when: ('preinstall' not in ansible_run_tags)
