#########################################################################
# Title:         Lidarr: Suitarr Migration Tasks                        #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Suitarr Migration Tasks
# This file contains tasks for migrating from Suitarr to Lidarr.

# Check if the /opt/lidarr directory exists.
- name: Suitarr Migration | Check folder exists
  stat:
    path: /opt/lidarr
  register: folder

# Check if the /opt/lidarr/Lidarr subdirectory exists.
- name: Suitarr Migration | Check subfolder1 exists
  stat:
    path: /opt/lidarr/Lidarr
  register: subfolder1

# If both directories exist, move the contents of the subdirectory to the parent
# directory and set the correct ownership. This is to handle a change in the
# directory structure from a previous version.
- name: Suitarr Migration | Move 'Lidarr' subfolder to 'lidarr' folder
  shell: |
    mv /opt/lidarr/Lidarr/* /opt/lidarr
    chown -R {{ user.name }}:{{ user.name }} /opt/lidarr
  when: (folder.stat.exists) and (subfolder1.stat.exists)
