#########################################################################
# Title:         Hetzner NFS: Hetzner NFS UnMount Task                  #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Hetzner NFS Unmount Tasks
# This file contains tasks for unmounting the Hetzner NFS share.

# Check if the nfs_vlan.service file exists.
- name: Check 'nfs_vlan.service' exists
  stat:
    path: '/etc/systemd/system/nfs_vlan.service'
  register: nfs_vlan_service

# Stop and disable the nfs_vlan.service.
- name: Stop 'nfs_vlan.service'
  systemd:
    state: stopped
    name: nfs_vlan
    daemon_reload: yes
    enabled: no
  when: nfs_vlan_service.stat.exists

# Uninstall the NFS client packages.
- name: Uninstall nfs requirements
  apt:
    state: absent
    name:
      - rpcbind
      - nfs-common

# Remove the configuration files and directories.
- name: Remove files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/systemd/system/nfs_vlan.service"
    - "/etc/hosts.allow"
    - "/etc/hosts.deny"
    - "/opt/hetzner_nfs"
    - "/mnt/feeder"

 # unionfs edits
# The following tasks revert the changes made to the unionfs.service file.

# Remove the 'After' directive for init_vlan.service from the unionfs.service file.
- name: Remove 'After=init_vlan.service' in 'unionfs.service'
  lineinfile:
    path: /etc/systemd/system/unionfs.service
    regexp: '(^After\=.*)\sinit_vlan\.service\s(.*)'
    line: '\1 \2'
    state: present
    backrefs: yes
  when: unionfs_service.stat.exists

# Replace /mnt/feeder with /mnt/local in the unionfs.service file.
- name: Replace '/mnt/feeder' with '/mnt/local' in 'unionfs.service'
  replace:
    path: /etc/systemd/system/unionfs.service
    regexp: "\\/mnt\\/feeder"
    replace: '/mnt/local'
  when: unionfs_service.stat.exists

  # mergerfs edits
# The following tasks revert the changes made to the mergerfs.service file.

# Remove the 'After' directive for init_vlan.service from the mergerfs.service file.
- name: Remove 'After=init_vlan.service' in 'mergerfs.service'
  lineinfile:
    path: /etc/systemd/system/mergerfs.service
    regexp: '(^After\=.*)\sinit_vlan\.service\s(.*)'
    line: '\1 \2'
    state: present
    backrefs: yes
  when: mergerfs_service.stat.exists

# Replace /mnt/feeder with /mnt/local in the mergerfs.service file.
- name: Replace '/mnt/feeder' with '/mnt/local' in 'mergerfs.service'
  replace:
    path: /etc/systemd/system/mergerfs.service
    regexp: "\\/mnt\\/feeder"
    replace: '/mnt/local'
  when: mergerfs_service.stat.exists
