#########################################################################
# Title:         Cloudbox: Hostess Role                                 #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Hostess Tasks
# This is the main task file for the hostess role. It installs hostess, a tool
# for managing /etc/hosts.

# Get the download URL for the latest release of hostess for Linux AMD64.
- name: Get latest hostess URL
  shell: curl -s https://api.github.com/repos/cbednarski/hostess/releases/latest | jq -r ".assets[] | select(.name | test(\"linux_amd64\")) | .browser_download_url"
  args:
    executable: /bin/bash
  register: hostess_download_url
  ignore_errors: yes

# Download and install hostess.
- name: Install hostess
  get_url:
    url:  "{{ hostess_download_url.stdout | default('https://github.com/cbednarski/hostess/releases/download/v0.3.0/hostess_linux_amd64',true) }}"
    dest: /usr/local/bin/hostess
    mode: 0775
    owner: root
    group: root
    force: yes
    validate_certs: no
  ignore_errors: yes
  register: x

# Get the installed version of hostess.
- name: "Get hostess version"
  shell: "/usr/local/bin/hostess --version | head -n 1 | awk '{ print $3 }'"
  register: hostess_version
  ignore_errors: yes
  when: x is success

# Display the installed version of hostess.
- name: "Display hostess version"
  debug:
    msg: "hostess {{ hostess_version.stdout }} installed."
  when: x is success

# If the installation failed, display an error message.
- debug:
    msg: "hostess install failed."
  when: x is not success
