#########################################################################
# Title:         Cloudbox: Cloudflare Role                              #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Cloudflare Tasks
# This is the main task file for the Cloudflare role. It includes other task
# files from the subtasks directory.

- name: Variables Task
  import_tasks: "subtasks/variables.yml"
  ignore_errors: yes

- name: Purge Cache Task
  import_tasks: "subtasks/purge_cache.yml"
  ignore_errors: yes

- name: Page Rules Task
  import_tasks: "subtasks/page_rules.yml"
  ignore_errors: yes
