#########################################################################
# Title:         Cloudbox: airdcpp Role                                 #
# Author(s):     l3uddz                                                 #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  gangefors/airdcpp-webclient                            #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# airdcpp Tasks

# Include the cloudflare-dns role to set the DNS record for airdcpp.
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare-dns
  vars:
    subdomain: airdcpp
  when: cloudflare_enabled

# Ensure that any previous airdcpp container is removed before creating a new one.
- name: Stop and remove any existing container
  docker_container:
    name: airdcpp
    state: absent

# Create the necessary directories for airdcpp configuration and downloads.
- name: Create airdcpp directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/airdcpp
    - /mnt/local/downloads/airdcpp
    - /mnt/local/downloads/airdcpp/Movies
    - /mnt/local/downloads/airdcpp/TV
    - /mnt/local/downloads/airdcpp/4K
    - /mnt/local/downloads/airdcpp/4K/Movies
    - /mnt/local/downloads/airdcpp/4K/TV

# Check if the WebServer.xml configuration file already exists.
- name: Check WebServer.xml exists
  stat:
    path: "/opt/airdcpp/WebServer.xml"
  register: webserver_xml

# Check if the DCPlusPlus.xml configuration file already exists.
- name: Check DCPlusPlus.xml exists
  stat:
    path: "/opt/airdcpp/DCPlusPlus.xml"
  register: dcplusplus_xml

# Copy the default WebServer.xml file if it doesn't already exist.
- name: Import default 'WebServer.xml'
  copy:
    src: WebServer.xml
    dest: /opt/airdcpp/WebServer.xml
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    force: yes
  when: not webserver_xml.stat.exists

# Copy the default DCPlusPlus.xml file if it doesn't already exist.
- name: Import default 'DCPlusPlus.xml'
  copy:
    src: DCPlusPlus.xml
    dest: /opt/airdcpp/DCPlusPlus.xml
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    force: yes
  when: not dcplusplus_xml.stat.exists

# Create and start the airdcpp Docker container with the specified configuration.
- name: Create and start container
  docker_container:
    name: airdcpp
    image: "gangefors/airdcpp-webclient"
    pull: yes
    published_ports:
      - "127.0.0.1:2617:5600"
      - "127.0.0.1:7327:5601"
      - "21248:21248"
      - "21248:21248/udp"
      - "21249:21249"
    user: "{{ uid }}:{{ gid }}"
    env:
      VIRTUAL_HOST: "airdcpp.{{ user.domain }}"
      VIRTUAL_PORT: 5600
      LETSENCRYPT_HOST: "airdcpp.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/airdcpp:/.airdcpp"
      - "/mnt/local/downloads/airdcpp:/Downloads"
      - "/mnt:/mnt"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - airdcpp
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
